import { NgModule } from "@angular/core";
import { 
    TuiTextfieldControllerModule, 
    TuiButtonModule, 
    TuiDropdownModule, 
    TuiLinkModule, 
    TuiExpandModule, 
    TuiPrimitiveCheckboxModule,
    TuiErrorModule,
    TuiAlertModule,
    TuiRootModule,
    TuiDataListModule,
    TuiHintModule
} from "@taiga-ui/core";
import {TuiDataListWrapperModule, TuiInputCopyModule, TuiInputModule, TuiInputNumberModule, TuiIslandModule, TuiRadioModule, TuiSelectModule} from '@taiga-ui/kit';
import {TuiActiveZoneModule, TuiAutoFocusModule} from '@taiga-ui/cdk';
import {
    TuiAlignContentModule,
    TuiCodeModule,
    TuiColorEditModule,
    TuiColorPickerModule,
    TuiColorSelectorModule,
    TuiDetailsModule,
    TuiEditLinkModule,
    TuiEditorImagePreviewModule,
    TuiEditorModule,
    TuiEditorSocketModule,
    TuiFlatPickerModule,
    TuiFontSizeModule,
    TuiFontStyleModule,
    TuiHighlightColorModule,
    TuiImageEditorModule,
    TuiInputColorModule,
    TuiLinearMultiPickerModule,
    TuiLinearPickerModule,
    TuiListConfigsModule,
    TuiPaletteModule,
    TuiTableCellColorModule,
    TuiTableCreateModule,
    TuiTableMergeCellsModule,
    TuiTableRowColumnManagerModule,
    TuiTableSizeSelectorModule,
    TuiTextColorModule,
    TuiTiptapEditorModule,
    TuiToolbarModule
} from '@taiga-ui/addon-editor';

@NgModule({
    exports: [
    TuiInputModule,
    TuiTextfieldControllerModule,
    TuiButtonModule,
    TuiDropdownModule,
    TuiActiveZoneModule,
    TuiLinkModule,
    TuiExpandModule,
    TuiIslandModule,
    TuiPrimitiveCheckboxModule,  
    TuiCodeModule,
    TuiColorEditModule,
    TuiColorPickerModule,
    TuiColorSelectorModule,
    TuiDetailsModule,
    TuiEditLinkModule,
    TuiEditorImagePreviewModule,
    TuiEditorModule,
    TuiEditorSocketModule,
    TuiFlatPickerModule,
    TuiFontSizeModule,
    TuiFontStyleModule,
    TuiHighlightColorModule,
    TuiImageEditorModule,
    TuiInputColorModule,
    TuiLinearMultiPickerModule,
    TuiLinearPickerModule,
    TuiListConfigsModule,
    TuiPaletteModule,
    TuiTableCellColorModule,
    TuiTableCreateModule,
    TuiTableMergeCellsModule,
    TuiTableRowColumnManagerModule,
    TuiTableSizeSelectorModule,
    TuiTextColorModule,
    TuiTiptapEditorModule,
    TuiAlignContentModule,
    TuiToolbarModule,
    TuiAutoFocusModule,
    TuiErrorModule,
    TuiAlertModule,
    TuiRootModule,
    TuiDataListModule,
    TuiDataListWrapperModule,
    TuiSelectModule,
    TuiInputNumberModule,
    TuiHintModule,
    TuiInputCopyModule
]})
export class TaigaModule{}